language: node_js
node_js:
  - "14.16"

cache: yarn

script:
  - yarn test:ci

deploy:
  - provider: script # Generate HTML for GitHub pages
    script: mkdir html && node src/cli.js -i schemata -o html/index.html
    edge: true
  - provider: pages:git # Deploy GitHub pages
    token: $GITHUB_API_TOKEN
    edge: true # opt in to dpl v2
    local_dir: html
    run:
      - ls -ltur
    verbose: true
